        ; Dragon 32 Screen Data
        ; Generated by screen_designer.py
        
        ; Screen initialization code
INIT_SCREEN:
        ; Clear screen with spaces
        LDX     #$0400
        LDA     #$20        ; space character
CLRSCR: STA     ,X+
        CMPX    #$0480
        BLO     CLRSCR
        
        ; Write screen content

        ; Row 0
        LDX     #1024
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+

        ; Row 2
        LDX     #1088
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #87        ; 'W'
        STA     ,X+
        LDA     #101        ; 'e'
        STA     ,X+
        LDA     #108        ; 'l'
        STA     ,X+
        LDA     #99        ; 'c'
        STA     ,X+
        LDA     #111        ; 'o'
        STA     ,X+
        LDA     #109        ; 'm'
        STA     ,X+
        LDA     #101        ; 'e'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #116        ; 't'
        STA     ,X+
        LDA     #111        ; 'o'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #68        ; 'D'
        STA     ,X+
        LDA     #114        ; 'r'
        STA     ,X+
        LDA     #97        ; 'a'
        STA     ,X+
        LDA     #103        ; 'g'
        STA     ,X+
        LDA     #111        ; 'o'
        STA     ,X+
        LDA     #110        ; 'n'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #51        ; '3'
        STA     ,X+
        LDA     #50        ; '2'
        STA     ,X+
        LDA     #33        ; '!'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+

        ; Row 4
        LDX     #1152
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+

        ; Row 6
        LDX     #1216
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #80        ; 'P'
        STA     ,X+
        LDA     #114        ; 'r'
        STA     ,X+
        LDA     #101        ; 'e'
        STA     ,X+
        LDA     #115        ; 's'
        STA     ,X+
        LDA     #115        ; 's'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #97        ; 'a'
        STA     ,X+
        LDA     #110        ; 'n'
        STA     ,X+
        LDA     #121        ; 'y'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #107        ; 'k'
        STA     ,X+
        LDA     #101        ; 'e'
        STA     ,X+
        LDA     #121        ; 'y'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #116        ; 't'
        STA     ,X+
        LDA     #111        ; 'o'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #99        ; 'c'
        STA     ,X+
        LDA     #111        ; 'o'
        STA     ,X+
        LDA     #110        ; 'n'
        STA     ,X+
        LDA     #116        ; 't'
        STA     ,X+
        LDA     #105        ; 'i'
        STA     ,X+
        LDA     #110        ; 'n'
        STA     ,X+
        LDA     #117        ; 'u'
        STA     ,X+
        LDA     #101        ; 'e'
        STA     ,X+
        LDA     #46        ; '.'
        STA     ,X+
        LDA     #46        ; '.'
        STA     ,X+
        LDA     #46        ; '.'
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+
        LDA     #32        ; ' '
        STA     ,X+

        ; Row 15
        LDX     #1504
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+
        LDA     #61        ; '='
        STA     ,X+

        RTS                     ; return from screen init
